### PR TITLE
Update OpenVX 1.1 headers

### PR DESCRIPTION
**Pull request by tlepley**

### CODE REVIEW

**Comment by fzbrill** [comment]
It looks like both Xin and Thierry are updating the headers.  Xin is updating the spec (pdf & html) and Thierry is doing the conformance tests.  Please work out between you who is doing the headers.

**Comment by oddhack** [comment]
@tlepley I suggested on #2 that @xwang-git remove the header package from that PR and you sync up to make sure the header package here has everything you need, then I can accept both. Maybe it's best to have separate PR for spec and header components as a general plan, going forward.

**Comment by oddhack** [comment]
@xwang-git @fzbrill if you could upvote or comment to confirm the header package update in this PR is what the WG wants, we can be done - I just accepted #2 with the spec updates.

**Comment by tlepley** [comment]
I'm closing this pull request as the top of maint-1.1 contains items not supposed to be in this branch. Xin will create a new pull request with headers in sync with the published spec.

**Pull request closed without merging**
