### PR TITLE
Update OpenVX1.1 spec pdf and html

### PR DESCRIPTION
**Pull request by xwang-git**
Update OpenVX1.1 spec pdf, html , headers based on voting decision at
03/15/2017 OpenVX group meeting.

### CODE REVIEW

**Comment by oddhack** [comment]
This looks good to me, except that the top-level index.php should be updated to mention the new spec / header package update dates (replacing "September / June 2016"). Or we could remove the update dates - they are hard to remember to keep current, and probably add little value to consumers of the specs. Whatever you guys like.

When that's added to the PR, and whenever the WG (which I guess means Frank, in this case) is ready, we can commit this.

**Comment by fzbrill** [comment]
We do need to update the index.php to the current (March 2017) date. This is because we decided that for minor updates like correcting or clarifying text with no IP or API impact, we don't change the version number.  So this will still be called 1.1.  The only way to know you have the latest is to look at the date on your document and compare  it with the date in the registry.  

I can't find evidence that index.php has been changed by this merge, so I assume it has not.  We need this.

**Comment by oddhack** [comment]
@xwang-git , I suggest that you update this PR to remove the header package and update the spec date in index.php. I'll accept it at that point per email from Frank. Then #3 can either be accepted as is, or if there's any meaningful difference between the header package here and the one in #3, #3 could be updated to match - that's up to you and @tlepley (whom I may not be able to link to from these comments, not sure) to sort out.

**Comment by xwang-git** [comment]
@oddhack  I have updated my commit as your suggested. Please review. Thanks!

**Pull request merged**
