### PR TITLE
Commit of OpenVX 1.2.1 spec, which was generated via AsciiDoc.  

### PR DESCRIPTION
**Pull request by fbrill3**
Also contains the KaTeX distribution for the equations.  I'm not entirely sure that's what we want, but it's the only thing I know how to do right now.  

But there is the following statement in the README.md in the katex directory:

* **Server side rendering:** KaTeX produces the same output regardless of browser or environment, so you can pre-render expressions using Node.js and send them as plain HTML.

Maybe we could do this?

BTW, I also moved the link to the OpenCL interop extension to put it in alphabetical order with the other extensions.  Not sure this is the best order, but we should have *some* order.

### CODE REVIEW

**Comment by oddhack** [comment]
We can go with this, but two questions:

* do you want to continue publishing the 1.2 spec in parallel, or just overlay the new asciidoctor version on top of the current specs/1.2/ ? There's a certain diffusion of link density that may work against Google search results with both specs/1.2 and specs/1.2.1, and also, people who may have bookmarked the 1.2 spec may not realize they're not getting the latest version.
* calling the HTML base file 'index.html' seems odd - why not OpenVX_Specification_1_2_1.html, like the PDF?

When do you want the MR accepted?

Regarding the offline rendering of KaTeX, there's a user-contributed MR in the Vulkan-Docs repository  which claims it does this. Neither Tobias nor I have had a chance to fully evaluate it, yet, but it will probably be a significant win (at the cost of making the build process take somewhat longer). I'm surprised the HTML VX 1.2 spec takes minutes to load and render for you; it takes about 10 seconds to load, render equations, and layout from a local copy on my several years old PC.

**Comment by fbrill3** [comment]
Jon, we still want to publish the old specs along side the new ones.  We've kept all previous versions on the registry (although we might take down the 1.0 spec since it's withdrawn and the grace period ended today). We agreed in the working group to make both 1.2.1 (AsciiDoc) and 1.2 (Doxygen) available.  Beginning with 1.3 there will be no Doxygen version to keep.  

Also, for as long as I have the rendering delay on the AsciiDoc HTML, I will continue use the Doxygen HTML.  I don't know what to tell you about how long it takes to render on my 2-year-old laptop, except that I don't have this issue on any other web page.  With this spec, even with the files on my local drive, Chrome shows a blank page for the first 30 seconds and then says "Page Unresponsive."  I click "Wait" and 30 seconds later I see the top of the page.  But it's frozen&mdash;it takes another minute before I can scroll smoothly through the document.  So it's a total of two minutes before I can actually use the document.

The filename index.html is historical from when we had a directory full of files and it really was just an index.  If you leave off the "index.html" and just use the directory name, browsers will look for index.html inside the directory by default.  For example, the URL https://www.khronos.org/registry/OpenVX/specs/1.2/html works.  Since there's only one file now, I have no problem with changing the name.  But maybe we'll have multiple files in the future?

We have a working group meeting tomorrow&mdash;let's wait until I discuss it with them before merging.

**Comment by oddhack** [comment]
Behavior when you specify a directory depends on the webserver configuration, not the browser, AFAIK. For example, going to https://www.khronos.org/registry/OpenVX/specs/1.2/ generates a directory listing, because there's no index.html and the server is configured to show listings in this case.

I suspect most people looking for the spec are going to be following a link from the top-level OpenVX-Registry/index.php, or just finding it in search engine results.

I don't know what's up with your laptop. A lot of people have complained about e.g. Vulkan HTML loading times but I haven't heard of complete lockups like that. Hopefully we can get some of the speed improvements tested and deployed soon.

**Comment by fbrill3** [comment]
Jon, we finally agreed to publish the AsciiDoc versions of the spec "as-is" and not delay any longer trying to get a "pre-rendered" solution.  Can you go ahead and accept the merge request now?  We have an approved provisional spec I need to create another MR for after this one is merged.

**Pull request merged**
